{
  "formatVersion": "1.1",
  "component": {
    "group": "mods.flammpfeil.slashblade",
    "module": "SlashBladeResharped-1.20.1",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SlashBladeResharped-1.20.1-0.6.1.jar",
          "url": "SlashBladeResharped-1.20.1-0.6.1.jar",
          "size": 3701188,
          "sha512": "01db854e1fa40c64287da7fc78871f57c0983cf3b868e926dd31efe801c618702173cee29524619e13cd6375009a0cfafa54f5e7b9dd97b29f8e16e826844b96",
          "sha256": "434e2c895e9b958b076728e98367ea71f6548ac22631fa2381d1450576964f1c",
          "sha1": "906b2e1e8bd7c75cc1b6c74440d0286b8e1dc4b0",
          "md5": "6933b91c08e2bd0fec3e5d12a4203ba4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-forge",
          "version": {
            "strictly": "1.0.2-rc1+1.20_mapped_official_1.20.1",
            "requires": "1.0.2-rc1+1.20_mapped_official_1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.1.44_mapped_official_1.20.1_at_af30762ab15aae8bdb90bb2efc36660b4dd01840"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "strictly": "15.2.0.27_mapped_official_1.20.1",
            "requires": "15.2.0.27_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "SlashBladeResharped-1.20.1-0.6.1.jar",
          "url": "SlashBladeResharped-1.20.1-0.6.1.jar",
          "size": 3701188,
          "sha512": "01db854e1fa40c64287da7fc78871f57c0983cf3b868e926dd31efe801c618702173cee29524619e13cd6375009a0cfafa54f5e7b9dd97b29f8e16e826844b96",
          "sha256": "434e2c895e9b958b076728e98367ea71f6548ac22631fa2381d1450576964f1c",
          "sha1": "906b2e1e8bd7c75cc1b6c74440d0286b8e1dc4b0",
          "md5": "6933b91c08e2bd0fec3e5d12a4203ba4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "SlashBladeResharped-1.20.1-0.6.1-sources.jar",
          "url": "SlashBladeResharped-1.20.1-0.6.1-sources.jar",
          "size": 3367012,
          "sha512": "2c754d8d7a45f0793bc4a44afb0a23b58bbed93174b2427f36a92967bc2199828d357e1f89922e2a61f2a1270454d0b1add2055aa1b8184e1285b70218783fee",
          "sha256": "270049e7928b463f92b9a7b959954a444d6c42d8fefd5bf1dbaed438fb6b16b7",
          "sha1": "0e7fe33985cda65c1f18e47ac8b4bbefc9a22bb5",
          "md5": "03b500d6b3fef01c6ad076a4056ea2d7"
        }
      ]
    }
  ]
}
