{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mcmod_mmf.mysterious_mountain_lib",
    "module": "MMLib",
    "version": "1.2.10-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MMLib-1.2.10-1.21.1.jar",
          "url": "MMLib-1.2.10-1.21.1.jar",
          "size": 382208,
          "sha512": "314ae54f35298f1b625dd0b16e9d8828a3ed434342e40460cdbfeb7c85aae6a9fbf374b2acc2d3556a2cf7cd746699e0c08d1a17e465e2a572f45c4337e16451",
          "sha256": "c7f240b8e1f55be4aee8e80a2f31c9fc20d88eb1fa526e81b650a7e6723e8ea1",
          "sha1": "a53d9aa018d3a2c59c481cb62bc1193e22b8f9ee",
          "md5": "2cfe4cfd0a51c47b5665b6cea9d5711c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MMLib-1.2.10-1.21.1.jar",
          "url": "MMLib-1.2.10-1.21.1.jar",
          "size": 382208,
          "sha512": "314ae54f35298f1b625dd0b16e9d8828a3ed434342e40460cdbfeb7c85aae6a9fbf374b2acc2d3556a2cf7cd746699e0c08d1a17e465e2a572f45c4337e16451",
          "sha256": "c7f240b8e1f55be4aee8e80a2f31c9fc20d88eb1fa526e81b650a7e6723e8ea1",
          "sha1": "a53d9aa018d3a2c59c481cb62bc1193e22b8f9ee",
          "md5": "2cfe4cfd0a51c47b5665b6cea9d5711c"
        }
      ]
    }
  ]
}
